table Dim_Sector
	lineageTag: 67fb41a0-c6f0-5659-ada6-4a4e8da904dd

	column Sector_ID
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 6337002e-9e02-58aa-a60e-fc8267cc2361
		summarizeBy: none
		sourceColumn: Sector_ID

	column Sector_Naam
		dataType: string
		lineageTag: efceef7a-4c87-5f23-aafe-f566f92153bb
		summarizeBy: none
		sourceColumn: Sector_Naam

	partition Dim_Sector = m
		mode: import
		source =
				let
				    Bron = Csv.Document(LeesBron("dim_sector.csv"), [Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
				    Kop = Table.PromoteHeaders(Bron, [PromoteAllScalars = true]),
				    Typen = Table.TransformColumnTypes(Kop, {{"Sector_ID", Int64.Type}, {"Sector_Naam", type text}}, "en-US")
				in
				    Typen

	annotation PBI_ResultType = Table

