table Dim_Datum
	lineageTag: 664fc61b-d9b7-5bc0-a127-68f176535ace
	dataCategory: Time

	column Datum
		dataType: dateTime
		isKey
		formatString: dd-mm-yyyy
		lineageTag: 0a094ff4-6337-58ed-adfe-e806e4f9b492
		summarizeBy: none
		sourceColumn: Datum

	column Jaar
		dataType: int64
		formatString: 0
		lineageTag: afcd519b-c08e-5ec1-ac66-1b53a430cdec
		summarizeBy: none
		sourceColumn: Jaar

	column Maandnummer
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 6cb92789-fbd5-5664-ae73-76d8ab0bba18
		summarizeBy: none
		sourceColumn: Maandnummer

	column Maand
		dataType: string
		lineageTag: f0db6557-a597-553e-a0d7-f3be81c9a18f
		summarizeBy: none
		sourceColumn: Maand
		sortByColumn: JaarMaand

	column JaarMaand
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: c24573a5-9529-55e0-ad1d-983f29eb2198
		summarizeBy: none
		sourceColumn: JaarMaand

	column Kwartaal
		dataType: string
		lineageTag: f40a6e52-df50-5e84-a98d-63d28c87dbec
		summarizeBy: none
		sourceColumn: Kwartaal

	column Is_Prognoseperiode
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 450353aa-0d62-5f85-a8e5-16aff7fac721
		summarizeBy: none
		sourceColumn: Is_Prognoseperiode

	partition Dim_Datum = m
		mode: import
		source =
				let
				    Bron = Csv.Document(LeesBron("dim_datum.csv"), [Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
				    Kop = Table.PromoteHeaders(Bron, [PromoteAllScalars = true]),
				    Typen = Table.TransformColumnTypes(Kop, {{"Datum", type date}, {"Jaar", Int64.Type}, {"Maandnummer", Int64.Type}, {"Maand", type text}, {"JaarMaand", Int64.Type}, {"Kwartaal", type text}, {"Is_Prognoseperiode", Int64.Type}}, "en-US")
				in
				    Typen

	annotation PBI_ResultType = Table
