table Fact_CO2_Sector
	lineageTag: 5964bcc4-888c-429f-85f1-9eac6bab5970

	column Datum
		dataType: dateTime
		isHidden
		formatString: Long Date
		lineageTag: 3ade5102-8f02-4f88-bc8b-4da16dba5614
		summarizeBy: none
		sourceColumn: Datum

		annotation UnderlyingDateTimeDataType = Date

	column Wijk_ID
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: f5a484b2-d4c9-4e63-84a5-b4c12d1ee866
		summarizeBy: none
		sourceColumn: Wijk_ID

	column Sector_ID
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: f74845c7-ca52-4873-82ff-657e118cc4ef
		summarizeBy: none
		sourceColumn: Sector_ID

	column Ton
		dataType: double
		isHidden
		lineageTag: 7cde0ac9-df8b-43b0-bf3a-584edcb3adab
		summarizeBy: none
		sourceColumn: Ton

	partition Fact_CO2_Sector = m
		mode: import
		source =
				let
				    Bron = Csv.Document(LeesBron("fact_co2_sector.csv"), [Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
				    Kop = Table.PromoteHeaders(Bron, [PromoteAllScalars = true]),
				    Typen = Table.TransformColumnTypes(Kop, {{"Datum", type date}, {"Wijk_ID", Int64.Type}, {"Sector_ID", Int64.Type}, {"Ton", type number}}, "en-US")
				in
				    Typen

	annotation PBI_ResultType = Table

