/// Jaardoelen per wijk en KPI. Datum = 1 januari van het jaar (toegevoegd in Power Query).
table Fact_Target
	lineageTag: d2f4747c-7bab-435b-8801-799ed4f4e35e

	column Jaar
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 9f960045-0b54-461a-ba63-eb8394755cb7
		summarizeBy: none
		sourceColumn: Jaar

	column Wijk_ID
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: c6b0f75b-b733-4705-a75f-eb89e6d8c3d5
		summarizeBy: none
		sourceColumn: Wijk_ID

	column KPI_ID
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: e21624c6-9b0d-4a6b-8d97-3f3314421b96
		summarizeBy: none
		sourceColumn: KPI_ID

	column Target
		dataType: double
		isHidden
		lineageTag: c0a8c3f4-ff84-49f4-9678-8b76ee0f66fd
		summarizeBy: none
		sourceColumn: Target

	column Datum
		dataType: dateTime
		isHidden
		formatString: Long Date
		lineageTag: ff8a0fa3-1e62-449c-8821-072632a05947
		summarizeBy: none
		sourceColumn: Datum

		annotation UnderlyingDateTimeDataType = Date

	partition Fact_Target = m
		mode: import
		source =
				let
				    Bron = Csv.Document(LeesBron("fact_target.csv"), [Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
				    Kop = Table.PromoteHeaders(Bron, [PromoteAllScalars = true]),
				    Typen = Table.TransformColumnTypes(Kop, {{"Jaar", Int64.Type}, {"Wijk_ID", Int64.Type}, {"KPI_ID", Int64.Type}, {"Target", type number}}, "en-US"),
				    Resultaat = Table.AddColumn(Typen, "Datum", each #date([Jaar], 1, 1), type date)
				in
				    Resultaat

	annotation PBI_ResultType = Table

