/// KPI-definities uit de bron; vaste AI-vervolgvragen buiten de workshopbasis.
table Dim_KPI
	lineageTag: 0b72c746-ed41-4dd5-a15d-2806f02c52d7

	column KPI_ID
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 8d272cd9-26d4-495c-a521-e04b0f57e41d
		summarizeBy: none
		sourceColumn: KPI_ID

	column KPI_Code
		dataType: string
		lineageTag: 27d39625-dffa-40b7-8f53-2bae7fcaf58b
		summarizeBy: none
		sourceColumn: KPI_Code

	column KPI_Naam
		dataType: string
		lineageTag: 55c7591b-7b4f-4e29-a71c-d8e1c6546c60
		summarizeBy: none
		sourceColumn: KPI_Naam
		sortByColumn: Volgorde

	column Eenheid
		dataType: string
		lineageTag: e34379e8-fadd-44c2-b222-f6a0de9c8fc0
		summarizeBy: none
		sourceColumn: Eenheid

	column Aggregatie
		dataType: string
		lineageTag: bdfaecb3-9ffd-474f-bd7c-4618925c2242
		summarizeBy: none
		sourceColumn: Aggregatie

	column Is_Ratio
		dataType: int64
		formatString: 0
		lineageTag: e3ab0564-b196-4115-a8ac-417a4ff6fac0
		summarizeBy: none
		sourceColumn: Is_Ratio

	column Hoger_Is_Beter
		dataType: int64
		formatString: 0
		lineageTag: 6be10554-9773-4732-ba8e-0ddd21ecb6c4
		summarizeBy: none
		sourceColumn: Hoger_Is_Beter

	column Thema
		dataType: string
		lineageTag: 91bc1f5f-17c3-46e7-a3b9-820278de140b
		summarizeBy: none
		sourceColumn: Thema

	column Volgorde
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 9b8bc0c1-dab7-41f2-b74e-43c0b77edc7a
		summarizeBy: none
		sourceColumn: Volgorde

	/// Rekenkolom: 1 voor KPI's in procenten (trend in procentpunt).
	column Is_Percentage = IF ( Dim_KPI[Eenheid] = "%", 1, 0 )
		dataType: int64
		formatString: 0
		lineageTag: cb7bc0c8-15f0-48e8-a1e4-065de65ae5b5
		summarizeBy: none

	partition Dim_KPI = m
		mode: import
		source =
				let
				    Bron = Csv.Document(LeesBron("dim_kpi.csv"), [Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
				    Kop = Table.PromoteHeaders(Bron, [PromoteAllScalars = true]),
				    Typen = Table.TransformColumnTypes(Kop, {{"KPI_ID", Int64.Type}, {"KPI_Code", type text}, {"KPI_Naam", type text}, {"Eenheid", type text}, {"Aggregatie", type text}, {"Is_Ratio", Int64.Type}, {"Hoger_Is_Beter", Int64.Type}, {"Thema", type text}, {"Volgorde", Int64.Type}}, "en-US"),
				    Benoemd = Table.TransformColumns(Typen, {{"KPI_Naam", each if _ = "Bevolkingsgroei" then "Inwoners" else if _ = "Energieverbruik per huishouden" then "Gemiddeld maandverbruik per huishouden" else _, type text}})
				in
				    Benoemd

	annotation PBI_ResultType = Table

