table Dim_Wijk
	lineageTag: 4961b47d-a05b-52c4-a9d1-4c597fe84aa0

	column Wijk_ID
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 993c231e-f7e6-5d84-a30e-e9a52e53f6e3
		summarizeBy: none
		sourceColumn: Wijk_ID

	column Wijk_Naam
		dataType: string
		lineageTag: 75045202-6d73-57b2-a7d3-8a27b8225db0
		summarizeBy: none
		sourceColumn: Wijk_Naam

	partition Dim_Wijk = m
		mode: import
		source =
				let
				    Bron = Csv.Document(LeesBron("dim_wijk.csv"), [Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
				    Kop = Table.PromoteHeaders(Bron, [PromoteAllScalars = true]),
				    Typen = Table.TransformColumnTypes(Kop, {{"Wijk_ID", Int64.Type}, {"Wijk_Naam", type text}}, "en-US")
				in
				    Typen

	annotation PBI_ResultType = Table
