table Dim_KPI
	lineageTag: 4b412825-7a1e-51f9-adc4-f8406fddba42

	column KPI_ID
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: e8a7b70a-0d5d-580a-ab65-7775387588ac
		summarizeBy: none
		sourceColumn: KPI_ID

	column KPI_Code
		dataType: string
		lineageTag: 05062bb6-0a84-54f7-a8d1-ec68832e6232
		summarizeBy: none
		sourceColumn: KPI_Code

	column KPI_Naam
		dataType: string
		lineageTag: c7109054-499e-58fb-ac00-dab4da9cea7a
		summarizeBy: none
		sourceColumn: KPI_Naam
		sortByColumn: Volgorde

	column Eenheid
		dataType: string
		lineageTag: 31698770-24ba-593d-a86d-08e2d93a1462
		summarizeBy: none
		sourceColumn: Eenheid

	column Domein
		dataType: string
		lineageTag: 3d02cacd-bc84-5f95-a8ff-fdbfb38fd067
		summarizeBy: none
		sourceColumn: Domein

	column Hoger_Is_Beter
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: a52194eb-5b48-52cb-a0e5-58ec5f0d7178
		summarizeBy: none
		sourceColumn: Hoger_Is_Beter

	column Periode
		dataType: string
		lineageTag: 8d86035f-8edb-5725-ac99-156caadd59ec
		summarizeBy: none
		sourceColumn: Periode

	column Volgorde
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 4eeb50b8-69da-5da2-ab86-0549e0e9470d
		summarizeBy: none
		sourceColumn: Volgorde

	partition Dim_KPI = m
		mode: import
		source =
				let
				    Bron = Csv.Document(LeesBron("dim_kpi.csv"), [Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
				    Kop = Table.PromoteHeaders(Bron, [PromoteAllScalars = true]),
				    Typen = Table.TransformColumnTypes(Kop, {{"KPI_ID", Int64.Type}, {"KPI_Code", type text}, {"KPI_Naam", type text}, {"Eenheid", type text}, {"Domein", type text}, {"Hoger_Is_Beter", Int64.Type}, {"Periode", type text}, {"Volgorde", Int64.Type}}, "en-US")
				in
				    Typen

	annotation PBI_ResultType = Table
