/// Jaardoelen per wijk en KPI. Datum = 1 januari van het jaar (toegevoegd in Power Query).
table Fact_Target
	lineageTag: 5a029c2f-cb16-49cd-b3a4-3c941a0e1730

	column Jaar
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 22f03d3a-9137-40f3-be5e-98686ca2d48c
		summarizeBy: none
		sourceColumn: Jaar

	column Wijk_ID
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 3e5f8fa2-29e4-4ec0-98ef-fc48cfad4799
		summarizeBy: none
		sourceColumn: Wijk_ID

	column KPI_ID
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: e2e7711e-082f-479c-b5f6-18e12fe0a3f9
		summarizeBy: none
		sourceColumn: KPI_ID

	column Target
		dataType: double
		isHidden
		lineageTag: 11b68998-b306-4e9f-916d-a28f8ad13bba
		summarizeBy: none
		sourceColumn: Target

	column Datum
		dataType: dateTime
		isHidden
		lineageTag: 9e144a89-6f83-4efc-a9a7-5cc2a39331ae
		summarizeBy: none
		sourceColumn: Datum

	partition Fact_Target = m
		mode: import
		source =
				let
				    Bron = Csv.Document(LeesBron("fact_target.csv"), [Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
				    Kop = Table.PromoteHeaders(Bron, [PromoteAllScalars = true]),
				    Typen = Table.TransformColumnTypes(Kop, {{"Jaar", Int64.Type}, {"Wijk_ID", Int64.Type}, {"KPI_ID", Int64.Type}, {"Target", type number}}, "en-US"),
				    Resultaat = Table.AddColumn(Typen, "Datum", each #date([Jaar], 1, 1), type date)
				in
				    Resultaat

	annotation PBI_ResultType = Table

