table Fact_KPI
	lineageTag: 7616913d-e034-4660-b202-af7cf120ad5d

	column Datum
		dataType: dateTime
		isHidden
		lineageTag: 6b037146-dc49-4266-a697-e30b22e74c31
		summarizeBy: none
		sourceColumn: Datum

	column Wijk_ID
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: c62ff3bc-262d-4c73-ad28-f286ee7b0217
		summarizeBy: none
		sourceColumn: Wijk_ID

	column KPI_ID
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 7178c201-9d4b-439f-a345-1d7cd9f35fe3
		summarizeBy: none
		sourceColumn: KPI_ID

	column Teller
		dataType: double
		isHidden
		lineageTag: 1fe6e6bd-17a1-4dcb-8d8e-3a29ebadd1bd
		summarizeBy: none
		sourceColumn: Teller

	column Noemer
		dataType: double
		isHidden
		lineageTag: cf349522-e7c6-4fda-a6e3-dd0327132693
		summarizeBy: none
		sourceColumn: Noemer

	partition Fact_KPI = m
		mode: import
		source =
				let
				    Bron = Csv.Document(LeesBron("fact_kpi.csv"), [Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
				    Kop = Table.PromoteHeaders(Bron, [PromoteAllScalars = true]),
				    Typen = Table.TransformColumnTypes(Kop, {{"Datum", type date}, {"Wijk_ID", Int64.Type}, {"KPI_ID", Int64.Type}, {"Teller", type number}, {"Noemer", type number}}, "en-US")
				in
				    Typen

	annotation PBI_ResultType = Table

